### ISSUE TITLE
Many Passwords support in Pass Station

### ISSUE THREAD

**Issue by noraj** [many-passwords/many-passwords#113]
In [Pass Station](https://github.com/noraj/pass-station) [v1.2.3](https://github.com/noraj/pass-station/releases/tag/v1.2.3) I added support for Many Passwords.

See examples at the end of [this page](https://noraj.github.io/pass-station/#/pages/examples).

**Comment by piechowiakmichal** [comment]
I am happy with it. I will mention this in [README](https://github.com/many-passwords/many-passwords/blob/main/README.md). Thanks!

**Comment by piechowiakmichal** [comment]
@noraj if you can, mention _Many passwords_ in README. This will help in the development of the project.
