### ISSUE TITLE
Change color when hovering over links and emphasize password count

### ISSUE THREAD

**Issue by IPJC** [many-passwords/many-passwords#139]
Hi, I was thinking that it would be nice to see the changes of color when hovering links.
The contrast is really nice on the fixed header, but I was thinking adding that kind of contrast to other links, especially on the three purple buttons on the Home page and About Us Page.

Search bar - Make the input font color darker for accessibility purposes.

Also, I was thinking about centering and emphasizing the password count on the Home Page. 

Let me know if this is something you are interested in.

**Comment by piechowiakmichal** [comment]
Hi!

I think that the animation applied on the three buttons below the title is sufficient. 
The current position of the buttons suits me. Maybe changing the link color when hovering over link in About Us Page is a good idea, but I'm not sure whether the current underline is not enough.

Search bar - maybe you can change Home button to Search bar in mobile view?

Current:

![image](https://user-images.githubusercontent.com/36797326/194961919-b094c9d8-7657-4f3b-ab0b-670df33e2ab0.png)

What I am thinking about:

![image](https://user-images.githubusercontent.com/36797326/194962051-781d9092-fa23-4945-95cc-15def8e99443.png)

But, I think a Search bar color change is not needed.

Thanks!

**Comment by piechowiakmichal** [comment]
Resolved in website repo [#24](https://github.com/many-passwords/many-passwords.github.io/pull/24)
