### ISSUE TITLE
Enhancing Contributing.md file

### ISSUE THREAD

**Issue by HimanshuMahto** [many-passwords/many-passwords#171]
The contributing.md file of this repo needs  an enhanced version of itself.

**Comment by piechowiakmichal** [comment]
Hi! What exactly do you think needs to be improved?

**Comment by HimanshuMahto** [comment]
The whole contributing file needs an enhancement as it looks kinda plain thought to add things like fork, branch creation and pushing the changes

**Comment by piechowiakmichal** [comment]
Closed, check my response in PR.
