### ISSUE TITLE
uniformize blank values

### ISSUE THREAD

**Issue by noraj** [many-passwords/many-passwords#61]
What about uniformizing `(blank)`,  `(none)`, `n/a`?

**Comment by piechowiakmichal** [comment]
I think it's a good idea. What do you think will be the best form?

**Comment by noraj** [comment]
I used to use `<blank>`.

`<>` are less likely used in comment or description like `()` can and also are often use to enclose special content.

**Comment by piechowiakmichal** [comment]
I think it's a good idea.

``<>`` it is often used in, for example, tutorials, so it shouldn't confuse the user.
