### ISSUE TITLE
Better automation (Github Action)

### ISSUE THREAD

**Issue by piechowiakmichal** [many-passwords/many-passwords#70]
I think better project automation is needed. I think to continue the current [script](https://github.com/many-passwords/many-passwords/blob/main/update.sh) in [Github Action](https://github.com/many-passwords/many-passwords/blob/main/.github/workflows/update.yaml). 

My ideas:
- looking for duplicates (any ideas how this could work?)
- replace empty entries with username and password onto ``<blank>``

Do you have any other idea? Write boldly in this issue.

It will be better if before you start working, write here how you see a given function. It will save my and your time.

**Comment by siddhantdixit** [comment]
@piechowiakmichal I would like to work on this issue. Can u assign this to me?

**Comment by piechowiakmichal** [comment]
Hi, of course. What do you want to do?

**Comment by siddhantdixit** [comment]
@piechowiakmichal Do we have to find duplicate passwords or usernames or Vendors? and

I will replace the field with empty username or password to <blank>.

**Comment by piechowiakmichal** [comment]
> Do we have to find duplicate passwords or usernames or Vendors?  

You have to compare all entry options to see if it is a duplicate. Do you have a better idea?

> I will replace the field with empty username or password to .  

Remember to replace it with ``<blank>``.

I will assigned you, thank you!

**Comment by siddhantdixit** [comment]
@piechowiakmichal  Thanks for assigning this to me! So the duplicated means that if all the fields are same in the CSV it will be counted as one? Like Row 229 and 230 

https://github.com/many-passwords/many-passwords/blob/main/passwords.csv#L229

https://github.com/many-passwords/many-passwords/blob/main/passwords.csv#L230

**Comment by piechowiakmichal** [comment]
@siddhantdixit yes, that's duplicated. Of these two entries, one entries should remain.
