### ISSUE TITLE
Simple Rest Api

### ISSUE THREAD

**Issue by rotirotirafa** [many-passwords/many-passwords#94]
I belive that an Api should be nice to provide info beyond web that can be used with any device.

Could i create this Rest Api ?

**Comment by piechowiakmichal** [comment]
Hi! How it's going?

**Comment by Emeka-Ugbanu-hub** [comment]
I would love to help with this

**Comment by piechowiakmichal** [comment]
Awesome, thanks!

**Comment by Emeka-Ugbanu-hub** [comment]
can you give me more information about this issue

**Comment by piechowiakmichal** [comment]
You can make it possible to retrieve credentials from the database by means of a request. Maybe it should be a library and not api? What do you think? If you have other ideas, go ahead.

**Comment by Emeka-Ugbanu-hub** [comment]
I would have loved to contribute, but I don't know the shell programming language

**Comment by piechowiakmichal** [comment]
@Emeka-Ugbanu-hub ok, no problem. Thanks!

**Comment by rotirotirafa** [comment]
@piechowiakmichal i'm creating the Api.. what you about host on Heroku after finish?

**Comment by piechowiakmichal** [comment]
@rotirotirafa Hi, sorry for response time. I'm closing this issue. I decided that api is not needed. I can't afford the project elsewhere than on Github.
